package com.wesleyhome.poi.api;

import com.google.common.base.CaseFormat;

public enum TableStyle {
    NONE,
    TABLE_STYLE_LIGHT_1,
    TABLE_STYLE_LIGHT_2,
    TABLE_STYLE_LIGHT_3,
    TABLE_STYLE_LIGHT_4,
    TABLE_STYLE_LIGHT_5,
    TABLE_STYLE_LIGHT_6,
    TABLE_STYLE_LIGHT_7,
    TABLE_STYLE_LIGHT_8,
    TABLE_STYLE_LIGHT_9,
    TABLE_STYLE_LIGHT_10,
    TABLE_STYLE_LIGHT_11,
    TABLE_STYLE_LIGHT_12,
    TABLE_STYLE_LIGHT_13,
    TABLE_STYLE_LIGHT_14,
    TABLE_STYLE_LIGHT_15,
    TABLE_STYLE_LIGHT_16,
    TABLE_STYLE_LIGHT_17,
    TABLE_STYLE_LIGHT_18,
    TABLE_STYLE_LIGHT_19,
    TABLE_STYLE_LIGHT_20,
    TABLE_STYLE_LIGHT_21,
    TABLE_STYLE_MEDIUM_1,
    TABLE_STYLE_MEDIUM_2,
    TABLE_STYLE_MEDIUM_3,
    TABLE_STYLE_MEDIUM_4,
    TABLE_STYLE_MEDIUM_5,
    TABLE_STYLE_MEDIUM_6,
    TABLE_STYLE_MEDIUM_7,
    TABLE_STYLE_MEDIUM_8,
    TABLE_STYLE_MEDIUM_9,
    TABLE_STYLE_MEDIUM_10,
    TABLE_STYLE_MEDIUM_11,
    TABLE_STYLE_MEDIUM_12,
    TABLE_STYLE_MEDIUM_13,
    TABLE_STYLE_MEDIUM_14,
    TABLE_STYLE_MEDIUM_15,
    TABLE_STYLE_MEDIUM_16,
    TABLE_STYLE_MEDIUM_17,
    TABLE_STYLE_MEDIUM_18,
    TABLE_STYLE_MEDIUM_19,
    TABLE_STYLE_MEDIUM_20,
    TABLE_STYLE_MEDIUM_21,
    TABLE_STYLE_MEDIUM_22,
    TABLE_STYLE_MEDIUM_23,
    TABLE_STYLE_MEDIUM_24,
    TABLE_STYLE_MEDIUM_25,
    TABLE_STYLE_MEDIUM_26,
    TABLE_STYLE_MEDIUM_27,
    TABLE_STYLE_MEDIUM_28,
    TABLE_STYLE_DARK_1,
    TABLE_STYLE_DARK_2,
    TABLE_STYLE_DARK_3,
    TABLE_STYLE_DARK_4,
    TABLE_STYLE_DARK_5,
    TABLE_STYLE_DARK_6,
    TABLE_STYLE_DARK_7,
    TABLE_STYLE_DARK_8,
    TABLE_STYLE_DARK_9,
    TABLE_STYLE_DARK_10,
    TABLE_STYLE_DARK_11;

    private TableStyle(){

    }

    @Override
    public String toString() {
        return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.UPPER_CAMEL, name());
    }
}
